/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "STM32F0xx.h"
#include "sct.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	 sct_init();
	 uint16_t i = 0;
	 volatile uint32_t del = 0;
	 sct_led(0x7A5C36DE);
	 for(del = 0; del<1000000;del++);

	while(1)
	{
		sct_value(i);
		i+=111;
		if(i>999) i = 0;
		for(del = 0; del<500000;del++);

	}
}
