/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "STM32F0xx.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t pole = 0b10101011101110111010101000000000;

int main(void)
{
	// GPIO SETUP

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOCEN; // enable CLK
	 GPIOA->MODER |= GPIO_MODER_MODER4_1; // LED1 = PA4, output
	 GPIOB->MODER |= GPIO_MODER_MODER0_1; // LED2 = PB0, output
	 GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	 GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0; // S1 = PC1, pullup


	while(1)
	{
		for(uint8_t i = 0; i<32; i++)
		{
			if(pole&0x10000000) GPIOA->BSRR = (1<<5); // set
			else GPIOA->BRR = (1<<5); // reset
			pole = pole <<1;
		}
		for (volatile uint32_t i = 0; i < 100000; i++); //wait
	}
}
